### ISSUE TITLE
No luck runing your examples

### ISSUE THREAD

**Issue by Ofer-Gal** [scottdj92/forms-with-formik#1]
this is with latest "creat-react-app --typescript"
first run I get: (14,5): JSX elements with no children must be self-closing
I remove the "</Formik>"  then I get: 
Lambdas are forbidden in JSX attributes due to their rendering performance impact
Any idea?

**Comment by scottdj92** [comment]
Thanks for opening an issue!

This project doesn't use create react app. It uses a custom ParcelJS server. Each example runs it. In each branch, it's required to install all packages and run `yarn run dev` to run the development server.

**Comment by scottdj92** [comment]
Closing due to age
